import type { AffixStat } from '../types/model'

export interface DefaultAffix {
  name: string
  stat: AffixStat
  value: number
  level: number
}

// İstanbul Kıyamet Vakti wiki "Tüm Efsunlar" sayfasından üretildi.
// Not: kaynak sayfada hem nokta hem virgül ONDALIK ayracı olarak kullanılmış.
// Seviye = kategori içindeki kademe sırası (zayıftan güçlüye).
export const DEFAULT_AFFIXES: DefaultAffix[] = [
  { name: "Kritik Artırıcı", stat: "critChance", value: 0.48, level: 1 },
  { name: "İğne Deliği Misali", stat: "critChance", value: 0.61, level: 2 },
  { name: "Horoz Gagası Misali", stat: "critChance", value: 0.8, level: 3 },
  { name: "Deniz Kestanesi Misali", stat: "critChance", value: 1.01, level: 4 },
  { name: "Epe Ucu Misali", stat: "critChance", value: 1.25, level: 5 },
  { name: "Yılan Isırığı Misali", stat: "critChance", value: 1.51, level: 6 },
  { name: "Rus Ruleti Emsali", stat: "critChance", value: 1.79, level: 7 },
  { name: "Ok Ucu Modeli", stat: "critChance", value: 2.08, level: 8 },
  { name: "Philothes Modeli", stat: "critChance", value: 2.394, level: 9 },
  { name: "Halit Girmenç İcadı", stat: "critChance", value: 2.721, level: 10 },
  { name: "H.G. İcadı(Mor)", stat: "critChance", value: 3.265, level: 11 },
  { name: "Saldırı Artırıcı", stat: "attack", value: 1.28, level: 1 },
  { name: "Kedi Emsali", stat: "attack", value: 2, level: 2 },
  { name: "Üstün İcadı", stat: "attack", value: 2.78, level: 3 },
  { name: "Hermann-Sermen Modeli", stat: "attack", value: 3.61, level: 4 },
  { name: "Avcı Usulü", stat: "attack", value: 4, level: 5 },
  { name: "Kaplan Emsali", stat: "attack", value: 5.28, level: 6 },
  { name: "Jandarma Ali Modeli", stat: "attack", value: 6.11, level: 7 },
  { name: "Dış Şehir Modeli", stat: "attack", value: 6.94, level: 8 },
  { name: "Tora Tora Modeli", stat: "attack", value: 7.77, level: 9 },
  { name: "Ardenneler Misali", stat: "attack", value: 8.6, level: 10 },
  { name: "Ardenneler Misali(Mor)", stat: "attack", value: 10.32, level: 11 },
  { name: "Savunma Artırıcı", stat: "defense", value: 1.28, level: 1 },
  { name: "Deniz Kabuklu", stat: "defense", value: 2, level: 2 },
  { name: "Kirpi Emsali", stat: "defense", value: 2.78, level: 3 },
  { name: "Ruh Kalkanlı", stat: "defense", value: 3.61, level: 4 },
  { name: "Karaktor İcadı", stat: "defense", value: 4.44, level: 5 },
  { name: "Yel Değirmeni Modeli", stat: "defense", value: 5.28, level: 6 },
  { name: "Maginot Modeli", stat: "defense", value: 6.11, level: 7 },
  { name: "Conk Usulü", stat: "defense", value: 6.94, level: 8 },
  { name: "Estergon İcadı", stat: "defense", value: 7.77, level: 9 },
  { name: "Plevne İcadı", stat: "defense", value: 8.6, level: 10 },
  { name: "Hasar Artırıcı", stat: "maxDamage", value: 23, level: 1 },
  { name: "Çekiç Başlı", stat: "maxDamage", value: 36, level: 2 },
  { name: "Örs Kütleli", stat: "maxDamage", value: 56, level: 3 },
  { name: "Adalı Emsali", stat: "maxDamage", value: 80, level: 4 },
  { name: "Çarşı Sokağı Usulü", stat: "maxDamage", value: 104, level: 5 },
  { name: "Meteor Tipi", stat: "maxDamage", value: 130, level: 6 },
  { name: "Eski ve Arkadaşları İcadı", stat: "maxDamage", value: 318, level: 7 },
  { name: "Alman Modeli", stat: "maxDamage", value: 336, level: 8 },
  { name: "Urban İcadı", stat: "maxDamage", value: 354, level: 9 },
  { name: "Yücelen Ekolü", stat: "maxDamage", value: 373, level: 10 },
  { name: "Yücelen Ekolü(Mor)", stat: "maxDamage", value: 448, level: 11 },
  { name: "Vücutçu Emsali", stat: "maxDamage", value: 522, level: 12 },
  { name: "Yeşilmen İcadı", stat: "maxDamage", value: 671, level: 13 },
  { name: "Zırh Artırıcı", stat: "armor", value: 0.0131, level: 1 },
  { name: "Fareadam Menşeili", stat: "armor", value: 0.0139, level: 2 },
  { name: "Eski Köprü Usulü", stat: "armor", value: 0.0152, level: 3 },
  { name: "Tosbağa Kabuğu Emsali", stat: "armor", value: 0.0167, level: 4 },
  { name: "Meteor Madeni Emsali", stat: "armor", value: 0.0184, level: 5 },
  { name: "Klaks Özel Modeli", stat: "armor", value: 0.0202, level: 6 },
  { name: "Timsah Derisi Emsali", stat: "armor", value: 0.0224, level: 7 },
  { name: "Demirci Dilek Modeli", stat: "armor", value: 0.0248, level: 8 },
  { name: "Karacin Modeli", stat: "armor", value: 0.0274, level: 9 },
  { name: "Solucan Modeli", stat: "armor", value: 0.0302, level: 10 },
  { name: "Solucan Modeli(Mor)", stat: "armor", value: 0.036, level: 11 },
  { name: "Fiziksel Hasar Artırıcı", stat: "magicPhysical", value: 6, level: 1 },
  { name: "Eski Bizans Usulü", stat: "magicPhysical", value: 9, level: 2 },
  { name: "Çeteci Usulü", stat: "magicPhysical", value: 14, level: 3 },
  { name: "GB İcadı", stat: "magicPhysical", value: 20, level: 4 },
  { name: "Yılan Dişi", stat: "magicPhysical", value: 26, level: 5 },
  { name: "Selim Bey İcadı", stat: "magicPhysical", value: 32, level: 6 },
  { name: "Nexus Modeli", stat: "magicPhysical", value: 80, level: 7 },
  { name: "Komet Modeli", stat: "magicPhysical", value: 84, level: 8 },
  { name: "Kan Çalan Usulü", stat: "magicPhysical", value: 88, level: 9 },
  { name: "Fevzi Bey İcadı", stat: "magicPhysical", value: 93, level: 10 },
  { name: "Fevzi Bey İcadı(Mor)", stat: "magicPhysical", value: 112, level: 11 },
  { name: "Babil Modeli", stat: "magicPhysical", value: 130, level: 12 },
  { name: "Ensari İcadı", stat: "magicPhysical", value: 167, level: 13 },
  { name: "Ateş Hasarı Artırıcı", stat: "magicFire", value: 6, level: 1 },
  { name: "Demir Formüllü", stat: "magicFire", value: 9, level: 2 },
  { name: "Ateş Böceği Misali", stat: "magicFire", value: 14, level: 3 },
  { name: "Güneş Öncüsü Usulü", stat: "magicFire", value: 20, level: 4 },
  { name: "Ejder Nefesi Misali", stat: "magicFire", value: 26, level: 5 },
  { name: "Nemci Usulü", stat: "magicFire", value: 32, level: 6 },
  { name: "Petrol Destekli", stat: "magicFire", value: 80, level: 7 },
  { name: "Sera Modeli", stat: "magicFire", value: 84, level: 8 },
  { name: "Antik Mısır Tarzı", stat: "magicFire", value: 88, level: 9 },
  { name: "Tarsharss Modeli", stat: "magicFire", value: 93, level: 10 },
  { name: "Tarsharss Modeli(Mor)", stat: "magicFire", value: 112, level: 11 },
  { name: "Grand Camp Modeli", stat: "magicFire", value: 130, level: 12 },
  { name: "Nerull Modeli", stat: "magicFire", value: 167, level: 13 },
  { name: "Buz Hasarı Artırıcı", stat: "magicIce", value: 6, level: 1 },
  { name: "Erciyes Modeli", stat: "magicIce", value: 9, level: 2 },
  { name: "GB Usulü", stat: "magicIce", value: 14, level: 3 },
  { name: "Sibirya Usulü", stat: "magicIce", value: 20, level: 4 },
  { name: "Sudan Kalpli", stat: "magicIce", value: 26, level: 5 },
  { name: "Demirden İcadı", stat: "magicIce", value: 32, level: 6 },
  { name: "Olgunn İcadı", stat: "magicIce", value: 80, level: 7 },
  { name: "Buz Kristali Modeli", stat: "magicIce", value: 84, level: 8 },
  { name: "Nitrojen Modeli", stat: "magicIce", value: 88, level: 9 },
  { name: "Bilge Kağan Modeli", stat: "magicIce", value: 93, level: 10 },
  { name: "Bilge Kağan Modeli(Mor)", stat: "magicIce", value: 112, level: 11 },
  { name: "Alaska Modeli", stat: "magicIce", value: 130, level: 12 },
  { name: "Karamuk İcadı", stat: "magicIce", value: 167, level: 13 },
  { name: "Elektrik Hasarı Artırıcı", stat: "magicElectric", value: 6, level: 1 },
  { name: "Gerilim Modeli", stat: "magicElectric", value: 9, level: 2 },
  { name: "Cin Usulü", stat: "magicElectric", value: 14, level: 3 },
  { name: "Alatlı Modeli", stat: "magicElectric", value: 20, level: 4 },
  { name: "Şok Modeli", stat: "magicElectric", value: 26, level: 5 },
  { name: "Vatoz Emsali", stat: "magicElectric", value: 32, level: 6 },
  { name: "Köz Modeli", stat: "magicElectric", value: 80, level: 7 },
  { name: "Zincir Modeli", stat: "magicElectric", value: 84, level: 8 },
  { name: "Doğru Akım Destekli", stat: "magicElectric", value: 88, level: 9 },
  { name: "Azat Efendi İcadı", stat: "magicElectric", value: 93, level: 10 },
  { name: "Azat Efendi İcadı(Mor)", stat: "magicElectric", value: 112, level: 11 },
  { name: "Bolat Modeli", stat: "magicElectric", value: 130, level: 12 },
  { name: "Bakırezer Planı", stat: "magicElectric", value: 167, level: 13 },
  { name: "Asit Hasarı Artırıcı", stat: "magicAcid", value: 6, level: 1 },
  { name: "Karınca Emsali", stat: "magicAcid", value: 9, level: 2 },
  { name: "Katılaştırılmış", stat: "magicAcid", value: 14, level: 3 },
  { name: "GB Formüllü", stat: "magicAcid", value: 20, level: 4 },
  { name: "Ragıp Bey İcadı", stat: "magicAcid", value: 26, level: 5 },
  { name: "DB Patentli", stat: "magicAcid", value: 32, level: 6 },
  { name: "Maden Suyu Modeli", stat: "magicAcid", value: 80, level: 7 },
  { name: "Turnusol Modeli", stat: "magicAcid", value: 84, level: 8 },
  { name: "Joker Emsali", stat: "magicAcid", value: 88, level: 9 },
  { name: "Hayvan Modeli", stat: "magicAcid", value: 93, level: 10 },
  { name: "Hayvan Modeli(Mor)", stat: "magicAcid", value: 112, level: 11 },
  { name: "Temizlik Hastası Emsali", stat: "magicAcid", value: 130, level: 12 },
  { name: "Hünal Modeli", stat: "magicAcid", value: 167, level: 13 },
  { name: "Zehir Hasarı Artırıcı", stat: "magicPoison", value: 6, level: 1 },
  { name: "Tacir Kapsüllü", stat: "magicPoison", value: 9, level: 2 },
  { name: "Akrep Emsali", stat: "magicPoison", value: 14, level: 3 },
  { name: "Yaban Mantarlı", stat: "magicPoison", value: 20, level: 4 },
  { name: "Yılan Emsali", stat: "magicPoison", value: 26, level: 5 },
  { name: "Teiseba Usulü", stat: "magicPoison", value: 32, level: 6 },
  { name: "TncyEkoClgnnUyksz Modeli", stat: "magicPoison", value: 80, level: 7 },
  { name: "Şah Kobra Modeli", stat: "magicPoison", value: 84, level: 8 },
  { name: "Borgia Modeli", stat: "magicPoison", value: 88, level: 9 },
  { name: "Paracelsus Modeli", stat: "magicPoison", value: 93, level: 10 },
  { name: "Paracelsus Modeli(Mor)", stat: "magicPoison", value: 112, level: 11 },
  { name: "Gümüş Taşlı", stat: "magicPoison", value: 130, level: 12 },
  { name: "Ghost Formüllü", stat: "magicPoison", value: 167, level: 13 },
  { name: "Ateş Hasarı Veren", stat: "hasarFire", value: 12, level: 1 },
  { name: "Akkor Tipi", stat: "hasarFire", value: 19, level: 2 },
  { name: "GB Modeli", stat: "hasarFire", value: 28, level: 3 },
  { name: "Sancak Etkili", stat: "hasarFire", value: 39, level: 4 },
  { name: "Duman Destekli", stat: "hasarFire", value: 52, level: 5 },
  { name: "Kuvayi Milliye", stat: "hasarFire", value: 65, level: 6 },
  { name: "Gizit Modeli", stat: "hasarFire", value: 160, level: 7 },
  { name: "Magnezyum Destekli", stat: "hasarFire", value: 168, level: 8 },
  { name: "Mavi Alev Usulü", stat: "hasarFire", value: 177, level: 9 },
  { name: "Büyük Sahra Menşeli", stat: "hasarFire", value: 187, level: 10 },
  { name: "Büyük Sahra Menşeli(Mor)", stat: "hasarFire", value: 224, level: 11 },
  { name: "Topçu Tipi", stat: "hasarFire", value: 262, level: 12 },
  { name: "Erlik Emsali", stat: "hasarFire", value: 337, level: 13 },
  { name: "Buz Hasarı Veren", stat: "hasarIce", value: 12, level: 1 },
  { name: "Kutup Esintili", stat: "hasarIce", value: 19, level: 2 },
  { name: "Çamlıca Menşeili", stat: "hasarIce", value: 28, level: 3 },
  { name: "Eskimo Usulü", stat: "hasarIce", value: 39, level: 4 },
  { name: "Frederik İcadı", stat: "hasarIce", value: 52, level: 5 },
  { name: "Zwartan İcadı", stat: "hasarIce", value: 65, level: 6 },
  { name: "Karayel Etkili", stat: "hasarIce", value: 160, level: 7 },
  { name: "Kristal Modeli", stat: "hasarIce", value: 168, level: 8 },
  { name: "Grönland Usulü", stat: "hasarIce", value: 177, level: 9 },
  { name: "Nötron Yıldızı Emsali", stat: "hasarIce", value: 187, level: 10 },
  { name: "Elektrik Hasarı Veren", stat: "hasarElectric", value: 12, level: 1 },
  { name: "Volta Modeli", stat: "hasarElectric", value: 19, level: 2 },
  { name: "Necati Bey İcadı", stat: "hasarElectric", value: 28, level: 3 },
  { name: "Yüksek Gerilim Emsali", stat: "hasarElectric", value: 39, level: 4 },
  { name: "Edison Modeli", stat: "hasarElectric", value: 52, level: 5 },
  { name: "Mev Usulü", stat: "hasarElectric", value: 65, level: 6 },
  { name: "Etin Palpa İcadı", stat: "hasarElectric", value: 160, level: 7 },
  { name: "Tesla Modeli", stat: "hasarElectric", value: 168, level: 8 },
  { name: "Kehribarlı", stat: "hasarElectric", value: 177, level: 9 },
  { name: "Mesmer Modeli", stat: "hasarElectric", value: 187, level: 10 },
  { name: "Asit Hasarı Veren", stat: "hasarAcid", value: 12, level: 1 },
  { name: "Semender Emsali", stat: "hasarAcid", value: 19, level: 2 },
  { name: "Asit Yağmuru Emsali", stat: "hasarAcid", value: 28, level: 3 },
  { name: "Lavosier Modeli", stat: "hasarAcid", value: 39, level: 4 },
  { name: "Bohr Modeli", stat: "hasarAcid", value: 52, level: 5 },
  { name: "Derhi İcadı", stat: "hasarAcid", value: 65, level: 6 },
  { name: "Hasan 2 Modeli", stat: "hasarAcid", value: 160, level: 7 },
  { name: "Dalton Modeli", stat: "hasarAcid", value: 165, level: 8 },
  { name: "Kezzaplı", stat: "hasarAcid", value: 177, level: 9 },
  { name: "Zilfallon", stat: "hasarAcid", value: 187, level: 10 },
  { name: "Zilfallon(Mor)", stat: "hasarAcid", value: 224, level: 11 },
  { name: "Zehir Hasarı Veren", stat: "hasarPoison", value: 12, level: 1 },
  { name: "Fare Zehri Emsali", stat: "hasarPoison", value: 19, level: 2 },
  { name: "Kobra Yılanı Emsali", stat: "hasarPoison", value: 28, level: 3 },
  { name: "Çelik Haberci Usulü", stat: "hasarPoison", value: 39, level: 4 },
  { name: "Kara Mamba Emsali", stat: "hasarPoison", value: 52, level: 5 },
  { name: "Yalgın Bey Usulü", stat: "hasarPoison", value: 65, level: 6 },
  { name: "Karadul Modeli", stat: "hasarPoison", value: 160, level: 7 },
  { name: "Gül Dikeni Modeli", stat: "hasarPoison", value: 168, level: 8 },
  { name: "Hidrofis Emsali", stat: "hasarPoison", value: 177, level: 9 },
  { name: "Arsenikli", stat: "hasarPoison", value: 187, level: 10 },
  { name: "Arsenikli(Mor)", stat: "hasarPoison", value: 224, level: 11 },
  { name: "Ateş Direnci Artırıcı", stat: "resistFire", value: 26, level: 1 },
  { name: "Su Misali", stat: "resistFire", value: 28, level: 2 },
  { name: "Köpük Misali", stat: "resistFire", value: 30, level: 3 },
  { name: "Üstat Memduh İcadı", stat: "resistFire", value: 33, level: 4 },
  { name: "Demir Misali", stat: "resistFire", value: 37, level: 5 },
  { name: "GB Buz Destekli", stat: "resistFire", value: 41, level: 6 },
  { name: "Tazı Emsali", stat: "resistFire", value: 45, level: 7 },
  { name: "Umut Dergisi Modeli", stat: "resistFire", value: 50, level: 8 },
  { name: "Amyant Tipi", stat: "resistFire", value: 55, level: 9 },
  { name: "Aramit Tipi", stat: "resistFire", value: 60, level: 10 },
  { name: "Buz Direnci Artırıcı", stat: "resistIce", value: 26, level: 1 },
  { name: "Sabit Usta İcadı", stat: "resistIce", value: 28, level: 2 },
  { name: "Fok Emsali", stat: "resistIce", value: 30, level: 3 },
  { name: "Sekanslı", stat: "resistIce", value: 33, level: 4 },
  { name: "Oğuz Bey İcadı", stat: "resistIce", value: 37, level: 5 },
  { name: "Şimal Usulü", stat: "resistIce", value: 41, level: 6 },
  { name: "İlikçi Emsali", stat: "resistIce", value: 45, level: 7 },
  { name: "Derviş Hasan Usulü", stat: "resistIce", value: 50, level: 8 },
  { name: "Kemikkafa Tipi", stat: "resistIce", value: 55, level: 9 },
  { name: "Karakürk Emsali", stat: "resistIce", value: 60, level: 10 },
  { name: "Elektrik Direnci Artırıcı", stat: "resistElectric", value: 26, level: 1 },
  { name: "Plastik Emsali", stat: "resistElectric", value: 28, level: 2 },
  { name: "Bakırköy Usulü", stat: "resistElectric", value: 30, level: 3 },
  { name: "Çemberlitaş Usulü", stat: "resistElectric", value: 33, level: 4 },
  { name: "Faraday Modeli", stat: "resistElectric", value: 37, level: 5 },
  { name: "İnzar Bey İcadı", stat: "resistElectric", value: 41, level: 6 },
  { name: "Toprak Modeli", stat: "resistElectric", value: 45, level: 7 },
  { name: "Folklor Modeli", stat: "resistElectric", value: 50, level: 8 },
  { name: "Bardini İcadı", stat: "resistElectric", value: 55, level: 9 },
  { name: "Shen Kuo İcadı", stat: "resistElectric", value: 60, level: 10 },
  { name: "Asit Direnci Artırıcı", stat: "resistAcid", value: 26, level: 1 },
  { name: "Simyacı Usulü", stat: "resistAcid", value: 28, level: 2 },
  { name: "Şifacı Zeki Muadili", stat: "resistAcid", value: 30, level: 3 },
  { name: "Heybeliada Menşeili", stat: "resistAcid", value: 33, level: 4 },
  { name: "Sultan Buyruğu Emsali", stat: "resistAcid", value: 37, level: 5 },
  { name: "Sipayri Usulü", stat: "resistAcid", value: 41, level: 6 },
  { name: "Komodo Emsali", stat: "resistAcid", value: 45, level: 7 },
  { name: "Cam Formüllü", stat: "resistAcid", value: 50, level: 8 },
  { name: "Granit Modeli", stat: "resistAcid", value: 55, level: 9 },
  { name: "Vahşi Emsali", stat: "resistAcid", value: 60, level: 10 },
  { name: "Zehir Direnci Artırıcı", stat: "resistPoison", value: 26, level: 1 },
  { name: "Nargile Usulü", stat: "resistPoison", value: 28, level: 2 },
  { name: "Yoğurt Misali", stat: "resistPoison", value: 30, level: 3 },
  { name: "Zakkum Emsali", stat: "resistPoison", value: 33, level: 4 },
  { name: "Engerek Emsali", stat: "resistPoison", value: 37, level: 5 },
  { name: "Cin Kralı İcadı", stat: "resistPoison", value: 41, level: 6 },
  { name: "Aktar Şevket İcadı", stat: "resistPoison", value: 45, level: 7 },
  { name: "Beygir Emsali", stat: "resistPoison", value: 50, level: 8 },
  { name: "Garr Tipi", stat: "resistPoison", value: 55, level: 9 },
  { name: "Vadi Kobrası Emsali", stat: "resistPoison", value: 60, level: 10 },
  { name: "Derin Göl Emsali", stat: "maxKudret", value: 89, level: 1 },
  { name: "Dipsiz Kuyu Emsali", stat: "maxKudret", value: 104, level: 2 },
  { name: "Kurt Şaman Tarzı", stat: "maxKudret", value: 120, level: 3 },
  { name: "Kutadgu Bilig Modeli", stat: "maxKudret", value: 137, level: 4 },
  { name: "Kutadgu Bilig Modeli(Mor)", stat: "maxKudret", value: 165, level: 5 },
  { name: "Serçe Emsali", stat: "maxEnergy", value: 129, level: 1 },
  { name: "Işık Havuzu Emsali", stat: "maxEnergy", value: 163, level: 2 },
  { name: "Aktar Şevket Modeli", stat: "maxEnergy", value: 200, level: 3 },
  { name: "Farabi Modeli", stat: "maxEnergy", value: 239, level: 4 },
  { name: "Farabi Modeli(Mor)", stat: "maxEnergy", value: 358, level: 5 },
  { name: "İyileştirme Artırıcı", stat: "healing", value: 118, level: 1 },
  { name: "Nefes Emsali", stat: "healing", value: 126, level: 2 },
  { name: "Mağara Şamanı Modeli", stat: "healing", value: 133, level: 3 },
  { name: "İbn-i Sina Modeli", stat: "healing", value: 140, level: 4 },
  { name: "İbn-i Sina Modeli(Mor)", stat: "healing", value: 168, level: 5 },
  { name: "Mashar Osman Modeli", stat: "healing", value: 196, level: 6 },
  { name: "Asklepios Modeli", stat: "healing", value: 252, level: 7 },
  { name: "Büyü Kritik Artırıcı", stat: "magicCrit", value: 1.78, level: 1 },
  { name: "Merlin Modeli", stat: "magicCrit", value: 2.08, level: 2 },
  { name: "Ruh Çalan Emsali", stat: "magicCrit", value: 2.394, level: 3 },
  { name: "Cevriye Sultan Modeli", stat: "magicCrit", value: 2.721, level: 4 },
  { name: "Cevriye Sultan Modeli(Mor)", stat: "magicCrit", value: 3.2651, level: 5 },
  { name: "Berosus Modeli", stat: "magicCrit", value: 4, level: 6 },
  { name: "Antilop Emsali", stat: "moveSpeed", value: 2, level: 1 },
  { name: "Cansiperhane", stat: "critArmor", value: 10, level: 1 },
]
